name: 🚀 deploy to vercel
on:
  push:
    branches: [ master, develop ]
  repository_dispatch:
    types: 
      - trigger-deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 🌲 set deployment env
        if: ${{ github.ref == 'refs/heads/master' || github.event.action == 'trigger-deploy' }}
        run: |
          echo "VERCEL_ARGS=--prod" >> "$GITHUB_ENV"
          
      - name: 🎪 setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          
      - name: 👷 install dependencies
        run: npm i
        
      - name: 🚀 deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: ${{ env.VERCEL_ARGS }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
